export const productCategories = [
  {
    title: 'Marine Machinery Spare Parts',
    shortTitle: 'Marine Machinery Spares',
    slug: 'marine-machinery-spare-parts',
    icon: 'gear',
    image: '/categories/marine-engine-spare-parts.jpg',
    desc: 'Engine parts, pumps, seals, and OEM components for vessels.',
    items: [
      'Main engine and auxiliary engine parts',
      'Turbocharger components',
      'Fuel injection equipment',
      'Pumps — bilge, ballast, fuel, cooling',
      'Heat exchangers and coolers',
      'Seals, bearings, and gaskets',
      'Cylinder heads, liners, and pistons',
      'Governor and control system parts',
    ],
  },
  {
    title: 'Deck and Engine Consumables',
    shortTitle: 'Deck and Engine Consumables',
    slug: 'deck-engine-consumables',
    icon: 'anchor',
    image: '/categories/deck-and-engine.jpg',
    desc: 'Lubricants, chemicals, mooring materials, and maintenance kits.',
    items: [
      'Lubricating oils and greases',
      'Cleaning agents and chemicals',
      'Rope, wire, and mooring materials',
      'Paint and anti-corrosion coatings',
      'Welding rods and consumables',
      'PPE and personal protective equipment',
      'Engine room maintenance kits',
    ],
  },
  {
    title: 'Pumps, Valves and Piping',
    shortTitle: 'Pumps, Valves and Piping',
    slug: 'pumps-valves-piping',
    icon: 'valve',
    image: '/categories/pupmb-valves.jpeg',
    desc: 'Centrifugal pumps, industrial valves, flanges, and fittings.',
    items: [
      'Centrifugal and reciprocating pumps',
      'Gate, globe, ball, and butterfly valves',
      'Check valves and safety relief valves',
      'Flanges, fittings, and pipe couplings',
      'Hoses and flexible connections',
      'Strainers and filters',
    ],
  },
  {
    title: 'Electrical and Automation Components',
    shortTitle: 'Electrical and Automation',
    slug: 'electrical-automation',
    icon: 'bolt',
    image: '/categories/electrical-and-automation.png',
    desc: 'Switchgear, cables, sensors, and marine-grade electrical parts.',
    items: [
      'Circuit breakers and switchgear',
      'Cables and cable glands',
      'Control panels and automation components',
      'Sensors, transmitters, and indicators',
      'Transformers and starters',
      'Marine-grade electrical fittings',
    ],
  },
  {
    title: 'Navigation and Communication Equipment',
    shortTitle: 'Navigation and Communication',
    slug: 'navigation-communication',
    icon: 'compass',
    image: '/categories/navigational-and-communication.jpg',
    desc: 'GPS, AIS, VHF radios, radar systems, and navigation spares.',
    items: [
      'GPS and chart plotting systems',
      'AIS transponders and receivers',
      'VHF radios and GMDSS equipment',
      'Radar systems and components',
      'Echo sounders and depth sounders',
      'Navigation lights and spare parts',
    ],
  },
  {
    title: 'Safety and Firefighting Equipment',
    shortTitle: 'Safety and Firefighting',
    slug: 'safety-firefighting',
    icon: 'shield',
    image: '/categories/marine-fire-protection-maintenence.png',
    desc: 'Life-saving appliances, fire systems, and PPE for marine use.',
    items: [
      'Life jackets and immersion suits',
      'Life rafts and survival equipment',
      'Fire extinguishers and firefighting systems',
      'Fire detection equipment',
      'Breathing apparatus and SCBA',
      'Emergency lighting systems',
      'First aid kits and medical supplies',
    ],
  },
  {
    title: 'Hydraulic and Pneumatic Components',
    shortTitle: 'Hydraulic and Pneumatic',
    slug: 'hydraulic-pneumatic',
    icon: 'hydraulic',
    image: '/categories/Pneumatic-and-Hydraulic-Products-600x300-1.jpg',
    desc: 'Pumps, cylinders, hoses, actuators, and repair kits.',
    items: [
      'Hydraulic pumps and motors',
      'Hydraulic cylinders and actuators',
      'Control valves and solenoids',
      'Hydraulic hoses and fittings',
      'Pneumatic cylinders and actuators',
      'Air compressors and accessories',
      'Seals and repair kits',
    ],
  },
  {
    title: 'Industrial Tools and Workshop Consumables',
    shortTitle: 'Industrial Tools',
    slug: 'industrial-tools',
    icon: 'wrench',
    image: '/categories/industrial-tools.jpg',
    desc: 'Hand tools, measuring instruments, lifting equipment, and fasteners.',
    items: [
      'Hand tools and power tools',
      'Measuring instruments and gauges',
      'Cutting tools and grinding consumables',
      'Lifting equipment and slings',
      'Workshop machinery and accessories',
      'Fasteners — bolts, nuts, and fittings',
      'Storage and handling equipment',
    ],
  },
]
