export const servicesList = [
  {
    slug: 'marine-spare-parts',
    number: '01',
    shortTitle: 'Marine Spare Parts',
    icon: 'ship',
    title: 'Marine Equipment and Spare Parts Supply',
    intro: 'We supply a comprehensive range of marine equipment and spare parts to vessel operators, ship managers, and procurement teams across the UAE and Middle East region.',
    includes: [
      'Marine machinery spare parts and OEM components',
      'Deck equipment and deck consumables',
      'Engine room consumables and maintenance items',
      'Navigation and communication equipment',
      'Safety and firefighting equipment',
      'Hydraulic and pneumatic components',
      'Electrical and automation components',
      'Mooring equipment and accessories',
    ],
    closing: 'Whether you need a single gasket or a full dry docking supply package, we handle sourcing from our established network of manufacturers and authorised distributors.',
  },
  {
    slug: 'oilfield-equipment',
    number: '02',
    shortTitle: 'Oilfield Equipment',
    icon: 'oil',
    title: 'Oilfield Equipment and Industrial Supply',
    intro: 'We procure and supply oilfield and industrial equipment for upstream, midstream, and downstream operations across the region.',
    includes: [
      'Pumps — centrifugal, submersible, reciprocating',
      'Valves — gate, globe, ball, check, and control',
      'Piping materials and fittings',
      'Pipeline and process equipment',
      'Industrial tools and workshop consumables',
      'Instrumentation and control components',
      'Mechanical seals and gaskets',
    ],
    closing: 'Our team understands the critical nature of oilfield supply and works with urgency to ensure parts are sourced and delivered without unnecessary delays.',
  },
  {
    slug: 'marine-consultancy',
    number: '03',
    shortTitle: 'Consultancy',
    icon: 'consult',
    title: 'Marine Consultancy and Technical Support',
    intro: 'Beyond supply, we offer technical advisory services for equipment selection, procurement strategy, and vendor management.',
    includes: [
      'Technical advisory for vessel and plant operations',
      'Equipment specification and evaluation support',
      'Vendor selection and qualification assistance',
      'Procurement strategy for maintenance programmes',
      'Support for newbuild and retrofit projects',
    ],
    closing: 'Our consultancy service is designed for clients who want a knowledgeable partner — not just a supplier — to help make better procurement decisions.',
  },
  {
    slug: 'emergency-procurement',
    number: '04',
    shortTitle: 'Emergency',
    icon: 'emergency',
    title: 'Emergency Procurement Support',
    intro: 'When a vessel is in port and cannot sail, or a plant has an unplanned shutdown, our emergency procurement service is built for exactly these situations.',
    includes: [
      'Fast-response sourcing for critical spare parts',
      'Priority supplier engagement and expediting',
      'Same-day and next-day delivery within the UAE',
      'Regional logistics coordination for deliveries across the UAE and Middle East region',
      'Immediate contact for urgent requirements',
    ],
    closing: 'Emergency procurement is one of our core capabilities — we have the network, experience, and urgency to respond when it matters most.',
  },
  {
    slug: 'technical-sourcing',
    number: '05',
    shortTitle: 'Technical Sourcing',
    icon: 'sourcing',
    title: 'Technical Sourcing and Vendor Coordination',
    intro: 'OEM parts, obsolete components, and highly specified items require experience and the right supplier connections to locate.',
    includes: [
      'OEM and equivalent replacement parts',
      'Obsolete and hard-to-find component sourcing',
      'Multi-vendor coordination for large supply lists',
      'Cross-referencing and technical matching',
      'Supplier qualification and vetting',
    ],
    closing: 'We act as an extension of your procurement team — handling the searching, comparing, and coordinating so you don\'t have to.',
  },
  {
    slug: 'pipeline-equipment',
    number: '06',
    shortTitle: 'Pipeline Equipment',
    icon: 'pipeline',
    title: 'Pipeline and Process Equipment Supply',
    intro: 'We support oil and gas and petrochemical clients with procurement for pipeline construction, maintenance, and plant shutdown projects.',
    includes: [
      'Pipeline fittings, flanges, and pipe materials',
      'Process equipment — heat exchangers, separators, filters',
      'Pressure vessels and storage tanks',
      'Plant shutdown and turnaround supply packages',
      'Project-specific material lists and bulk procurement',
    ],
    closing: 'Our experience in project-based supply means we understand how to manage material lists, coordinate vendors, and deliver against project schedules.',
  },
]
